### ISSUE TITLE
Syncing break when event year created is 0000

### ISSUE THREAD

**Issue by tiffanyqi** [MaxFangX/calendar-analytics#3]
Found a bug where I sync my calendars, and the exception I get is "year out of range". I speculate it's because it's around 2010.

EDIT: This is because the year created is in 0000.

**Comment by MaxFangX** [comment]
Could you share the stack trace?

**Comment by tiffanyqi** [comment]
Environment:

Request Method: GET
Request URL: http://localhost:8000/v1/sync/?sync_all=true

Django Version: 1.8.4
Python Version: 2.7.10
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'cal',
 'api',
 'rest_framework',
 'social.apps.django_app.default',
 'loginas')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cal.middleware.UserBasedExceptionMiddleware')

Traceback:
File "/Users/Tiffany1/Desktop/temp/calenv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/Users/Tiffany1/Desktop/temp/calenv/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
2.         return view_func(_args, *_kwargs)
   File "/Users/Tiffany1/Desktop/temp/calenv/lib/python2.7/site-packages/django/views/generic/base.py" in view
3.             return self.dispatch(request, _args, *_kwargs)
   File "/Users/Tiffany1/Desktop/temp/calenv/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
4.             response = self.handle_exception(exc)
   File "/Users/Tiffany1/Desktop/temp/calenv/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
5.             response = handler(request, _args, *_kwargs)
   File "/Users/Tiffany1/Desktop/temp/calenv/lib/python2.7/site-packages/rest_framework/decorators.py" in handler
6.             return func(_args, *_kwargs)
   File "/Users/Tiffany1/Desktop/calendar-analytics/cal/api/views.py" in sync
7.             calendar.sync()
   File "/Users/Tiffany1/Desktop/calendar-analytics/cal/cal/models.py" in sync
8.             update_event(item)
   File "/Users/Tiffany1/Desktop/calendar-analytics/cal/cal/models.py" in update_event
9.                     g.created = parse_datetime(event['created'])
   File "/Users/Tiffany1/Desktop/temp/calenv/lib/python2.7/site-packages/django/utils/dateparse.py" in parse_datetime
10.         return datetime.datetime(**kw)

Exception Type: ValueError at /v1/sync/
Exception Value: year is out of range

**Comment by tiffanyqi** [comment]
{u'created': u'0000-12-29T00:00:00.000Z',

**Comment by MaxFangX** [comment]
Is this still a problem?

**Comment by tiffanyqi** [comment]
Yes, it still has this created field.

**Comment by MaxFangX** [comment]
I suppose the fix is to put a try/except around [this line](https://github.com/MaxFangX/calendar-analytics/blob/b1c03266027e52993917cc577a37492d6311a0aa/cal/cal/models.py#L175), and in the except block use the value of `g.updated` to fill in `g.created`. It's a stupid fix, but it's the only thing we can do given that Google's data is malformed. It would be helpful to include a quick comment explaining why we have the try/except and a link to this Github issue.

**Comment by andrewhuang** [comment]
Do we want to wrap all `parse_date(time)` calls with try-excepts? Seems like this could be an issue down the line if we only wrap this one.

**Comment by MaxFangX** [comment]
@andrewhuang Hmm perhaps. Though if our except still throws an error or fails to save the event its pointless. Perhaps we could catch all errors and log the malformed GEvents into another table with nullable constraints, and base our future patches off of the results we get. This way we can ensure at least that sync will always run (assuming no Auth errors or anything)

**Comment by MaxFangX** [comment]
Thoughts?

**Comment by andrewhuang** [comment]
>  Perhaps we could catch all errors and log the malformed GEvents into another table with nullable constraints, and base our future patches off of the results we get. 

I was thinking we could just have sane failsafe defaults whenever parsing fails (and an exception is raised). Events could also have a flag on whether or not we had to populate missing data, so that we can do the look-back that you've mentioned.

**Comment by MaxFangX** [comment]
What defaults could we use exactly? And if we have a flag, how would we know which field to look at / know what the malformed value is? 

Sounds like the best solution though

**Comment by tiffanyqi** [comment]
#109

**Comment by andrewhuang** [comment]
This will probably require further thought than we've given it on this thread. I've made [a card for this on Trello](https://trello.com/c/2uSorVVy/102-robust-event-syncing) so that we don't forget to revisit this.
