### ISSUE TITLE
Inconsistency in hours between shell and front-end for color category calculation

### ISSUE THREAD

**Issue by tiffanyqi** [MaxFangX/calendar-analytics#32]
Ways to reproduce (Tiffany's calendar, can try own calendar):

```
$ user = User.objects.get(id=3)
$ c = ColorCategory(label="primary", color=1,user=user)
$ c.hours()
  6885
```

When running the application itself, the graph says 42514 hours. Is it a problem that there's a discrepancy between these two numbers?

**Comment by MaxFangX** [comment]
You can look in the network tab and see if the API is returning 6885. If so, then there is a bug in the frontend graph implementation.

**Comment by tiffanyqi** [comment]
Confirmed, API is returning 42514. There may be a bug in the API.
