### ISSUE TITLE
Tags are only calculating primary calendar

### ISSUE THREAD

**Issue by tiffanyqi** [MaxFangX/calendar-analytics#5]
The hours field does not retrieve events on non-primary calendars, and thus is not outputting the correct value.

**Comment by MaxFangX** [comment]
This is intended behavior - handling multiple calendar logic in backend code is not performant

**Comment by tiffanyqi** [comment]
Hm, is there a way to ensure that tagging and color categories are able to calculate this information that's still performant?

**Comment by MaxFangX** [comment]
Yeah! We'll have all the events cached in our frontend, and make queries
that way.
