### ISSUE TITLE
Javascript inconsistently uses 2 space tabs and 4 space tabs

### ISSUE THREAD

**Issue by MaxFangX** [MaxFangX/calendar-analytics#54]

**Comment by jamesuejio** [comment]
How is this an issue? Can't we just mass format files?

**Comment by MaxFangX** [comment]
Yeah, someone just needs to do it after our open PR's are merged

**Comment by jamesuejio** [comment]
MaxFangX needs to do it

**Comment by MaxFangX** [comment]
Why don't you do it with yer fency IDE that removes spaces without you even knowing 💯 💯 👍 💯

**Comment by jamesuejio** [comment]
K I changed it in calendaranalytics.js to use 2 tabs. I checked through all the other .js files and they use 2 tabs.

**Comment by MaxFangX** [comment]
Rip me

**Comment by jalagar** [comment]
Huh? I thought I closed this

**Comment by jamesuejio** [comment]
What? Also try to use 2 spaces, but I'll change this asap.

**Comment by MaxFangX** [comment]
Ahaha looks like my comment posted a few days after I originally sent it via email
