### ISSUE TITLE
Events on click are yellow instead of white

### ISSUE THREAD

**Issue by jamesuejio** [MaxFangX/calendar-analytics#66]
I believe this is the culprit: 
https://github.com/MaxFangX/calendar-analytics/commit/b1c03266027e52993917cc577a37492d6311a0aa

**Comment by MaxFangX** [comment]
Does the color of these events depend on an attribute in the event object? 

I ask because the commit you referenced makes no changes in the frontend - it adds color in the backend. The frontend should be calling the backend appropriately and handling where the color added

**Comment by jamesuejio** [comment]
Uh I just added a style attribute to element.qtip, but I'm not sure maybe something in the back end overridded this? Have any ideas? I'm pretty sure it's this change because I had a branch that was old and the events were white.
