### ISSUE TITLE
Main README.md needs to be updated

### ISSUE THREAD

**Issue by MaxFangX** [MaxFangX/calendar-analytics#74]
I think the new one should include these things:
- Better tagline
- Completely revamped marketing copytext that reflects what typical calendar users and calendar loggers would be interested in
- All three of our names instead of just me
- A screenshot/gif of some cool parts of our app
- A "getting started" guide in case anyone random on the internet would like to try running our app. It would include instructions on how to get Google Calendar API keys and stuff from the Google API Console

Anything else we should include?

**Comment by MaxFangX** [comment]
The marketing text needs to be added to our logged out homepage as well:
![image](https://cloud.githubusercontent.com/assets/7884003/19870581/635a142e-9f6e-11e6-820b-c3cd8c757cfc.png)

**Comment by tiffanyqi** [comment]
@MaxFangX why would they need the Google API keys? It should just be 1) go to site 2) authorize google account 3) use the app

**Comment by MaxFangX** [comment]
@tiffanyqi You are talking about the end user experience. Recall how we had to set sensitive environment variables before running the app - those are our API keys. If a random person on Github wants to run our app, we can't just give them our API keys; we need to show them how they can get their own.

**Comment by tiffanyqi** [comment]
#119
